"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, UserSearch, Building2, Download, Check, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

interface InvestigationNextActionsProps {
  investigationId?: string;
  recruiterQuery?: string;
  companyQuery?: string;
  onAnalyzeAnother?: () => void;
  summaryData?: {
    id?: string;
    verdict?: string;
    riskScore?: number;
    confidence?: number;
    reasons?: string[];
    recommendations?: string[];
    jobText?: string;
    date?: string;
  };
}

export function InvestigationNextActions({
  investigationId,
  recruiterQuery,
  companyQuery,
  onAnalyzeAnother,
  summaryData,
}: InvestigationNextActionsProps) {
  const router = useRouter();
  const [downloaded, setDownloaded] = useState(false);

  const recommendations = summaryData?.recommendations || [];

  const handleDownloadSummary = () => {
    try {
      const dateStr = summaryData?.date || new Date().toISOString();
      const idStr = summaryData?.id || investigationId || "JOB-SCAN";
      const verdictStr = summaryData?.verdict || "ANALYZED";
      const scoreStr = summaryData?.riskScore !== undefined ? `${summaryData.riskScore}/100` : "N/A";

      const reportContent = [
        "==================================================",
        "           JOBSHIELD AI INVESTIGATION REPORT      ",
        "==================================================",
        `Investigation ID: ${idStr}`,
        `Date Generated:   ${dateStr}`,
        `Risk Assessment:  ${verdictStr}`,
        `Risk Score:       ${scoreStr}`,
        summaryData?.confidence ? `Confidence:       ${Math.round(summaryData.confidence > 1 ? summaryData.confidence : summaryData.confidence * 100)}%` : "",
        "",
        "--------------------------------------------------",
        "KEY FINDINGS & SIGNALS",
        "--------------------------------------------------",
        ...(summaryData?.reasons && summaryData.reasons.length > 0
          ? summaryData.reasons.map((r, i) => `[${i + 1}] ${r}`)
          : ["No primary risk reasons specified."]),
        "",
        "--------------------------------------------------",
        "RECOMMENDED NEXT ACTIONS",
        "--------------------------------------------------",
        ...(recommendations.length > 0
          ? recommendations.map((a, i) => `• ${a}`)
          : ["• Perform independent due diligence before proceeding with this opportunity."]),
        "",
        summaryData?.jobText ? "--------------------------------------------------\nANALYZED JOB TEXT SNIPPET\n--------------------------------------------------\n" + summaryData.jobText.substring(0, 500) + (summaryData.jobText.length > 500 ? "..." : "") : "",
        "",
        "==================================================",
        "Generated by JobShield AI — https://jobshield.ai",
        "=================================================="
      ].filter(Boolean).join("\n");

      const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `jobshield-report-${idStr.substring(0, 12)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    } catch (e) {
      console.error("Failed to generate summary download:", e);
    }
  };

  const handleAnalyzeClick = () => {
    if (onAnalyzeAnother) {
      onAnalyzeAnother();
    } else {
      router.push("/investigate");
    }
  };

  return (
    <section aria-label="Recommendations and Next Actions" className="space-y-4">
      <div>
        <h3 className="text-base font-serif text-slate-100 tracking-tight">Recommendations</h3>
        <p className="text-xs text-slate-400 font-sans mt-0.5">
          Guidance and protective steps based on detected indicators.
        </p>
      </div>

      <div className="rounded-lg border border-slate-800/80 bg-surface-elevated p-5 sm:p-6 shadow-sm space-y-5">
        {/* Recommendations list */}
        <div className="space-y-2">
          {recommendations.length > 0 ? (
            recommendations.map((rec, idx) => (
              <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-300 font-sans">
                <ShieldCheck className="h-4 w-4 text-blue-400 flex-shrink-0 mt-0.5" />
                <span className="leading-relaxed">{rec}</span>
              </div>
            ))
          ) : (
            <div className="flex items-start gap-2.5 text-xs text-slate-300 font-sans">
              <ShieldCheck className="h-4 w-4 text-blue-400 flex-shrink-0 mt-0.5" />
              <span className="leading-relaxed">Verify recruiter domain matches official public corporate records before exchanging sensitive information.</span>
            </div>
          )}
        </div>

        {/* Action buttons */}
        <div className="pt-4 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap items-center gap-2">
            {recruiterQuery && (
              <Link href={`/threat-intelligence?search=${encodeURIComponent(recruiterQuery)}`}>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-slate-800 bg-surface hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-sans"
                >
                  <UserSearch className="w-3.5 h-3.5 mr-1.5 text-purple-400" />
                  Check Recruiter
                </Button>
              </Link>
            )}

            {companyQuery && (
              <Link href={`/threat-intelligence?search=${encodeURIComponent(companyQuery)}`}>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-slate-800 bg-surface hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-sans"
                >
                  <Building2 className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                  Verify Company
                </Button>
              </Link>
            )}

            <Button
              onClick={handleDownloadSummary}
              variant="outline"
              size="sm"
              className="border-slate-800 bg-surface hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-sans"
            >
              {downloaded ? (
                <>
                  <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                  Report Downloaded
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5 mr-1.5 text-blue-400" />
                  Export Report (.txt)
                </>
              )}
            </Button>
          </div>

          <Button
            onClick={handleAnalyzeClick}
            size="sm"
            className="bg-blue-600 hover:bg-blue-500 text-white font-medium text-xs font-sans px-4 shadow-sm transition-all cursor-pointer"
          >
            Analyze Another Job
            <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
          </Button>
        </div>
      </div>
    </section>
  );
}
