"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, UserSearch, Building2, Download, Check, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

interface InvestigationNextActionsProps {
  investigationId?: string;
  recruiterQuery?: string;
  companyQuery?: string;
  onAnalyzeAnother?: () => void;
  summaryData?: {
    id?: string;
    verdict?: string;
    riskScore?: number;
    confidence?: number;
    reasons?: string[];
    recommendations?: string[];
    jobText?: string;
    date?: string;
  };
}

export function InvestigationNextActions({
  investigationId,
  recruiterQuery,
  companyQuery,
  onAnalyzeAnother,
  summaryData,
}: InvestigationNextActionsProps) {
  const router = useRouter();
  const [downloaded, setDownloaded] = useState(false);

  const handleDownloadSummary = () => {
    try {
      const dateStr = summaryData?.date || new Date().toISOString();
      const idStr = summaryData?.id || investigationId || "JOB-SCAN";
      const verdictStr = summaryData?.verdict || "ANALYZED";
      const scoreStr = summaryData?.riskScore !== undefined ? `${summaryData.riskScore}/100` : "N/A";

      const reportContent = [
        "==================================================",
        "           JOBSHIELD AI INVESTIGATION REPORT      ",
        "==================================================",
        `Investigation ID: ${idStr}`,
        `Date Generated:   ${dateStr}`,
        `Risk Assessment:  ${verdictStr}`,
        `Risk Score:       ${scoreStr}`,
        summaryData?.confidence ? `Confidence:       ${Math.round(summaryData.confidence * 100)}%` : "",
        "",
        "--------------------------------------------------",
        "KEY FINDINGS & SIGNALS",
        "--------------------------------------------------",
        ...(summaryData?.reasons && summaryData.reasons.length > 0
          ? summaryData.reasons.map((r, i) => `[${i + 1}] ${r}`)
          : ["No primary risk reasons specified."]),
        "",
        "--------------------------------------------------",
        "RECOMMENDED NEXT ACTIONS",
        "--------------------------------------------------",
        ...(summaryData?.recommendations && summaryData.recommendations.length > 0
          ? summaryData.recommendations.map((a, i) => `• ${a}`)
          : ["• Perform due diligence before responding to this opportunity."]),
        "",
        summaryData?.jobText ? "--------------------------------------------------\nANALYZED JOB TEXT SNIPPET\n--------------------------------------------------\n" + summaryData.jobText.substring(0, 500) + (summaryData.jobText.length > 500 ? "..." : "") : "",
        "",
        "==================================================",
        "Generated by JobShield AI — https://jobshield.ai",
        "=================================================="
      ].filter(Boolean).join("\n");

      const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `jobshield-report-${idStr.substring(0, 12)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    } catch (e) {
      console.error("Failed to generate summary download:", e);
    }
  };

  const handleAnalyzeClick = () => {
    if (onAnalyzeAnother) {
      onAnalyzeAnother();
    } else {
      router.push("/investigate");
    }
  };

  return (
    <div className="rounded-xl border border-slate-800 bg-[#090d16] p-5 sm:p-6 shadow-xl my-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-5">
        <div className="space-y-1">
          <h4 className="text-sm font-bold text-slate-100 uppercase tracking-wider font-mono">
            Next Actions
          </h4>
          <p className="text-xs text-slate-400">
            Verify related intelligence, export findings, or scan another job posting.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Check Recruiter (only when a query exists) */}
          {recruiterQuery && (
            <Link href={`/recruiters?search=${encodeURIComponent(recruiterQuery)}`}>
              <Button
                variant="outline"
                size="sm"
                className="border-slate-800 bg-slate-900/80 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-mono"
              >
                <UserSearch className="w-3.5 h-3.5 mr-1.5 text-purple-400" />
                Check Recruiter ({recruiterQuery})
              </Button>
            </Link>
          )}

          {/* Check Company (only when a company exists) */}
          {companyQuery && (
            <Link href={`/company-check?search=${encodeURIComponent(companyQuery)}`}>
              <Button
                variant="outline"
                size="sm"
                className="border-slate-800 bg-slate-900/80 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-mono"
              >
                <Building2 className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                Verify Company
              </Button>
            </Link>
          )}

          {/* Download Summary */}
          <Button
            onClick={handleDownloadSummary}
            variant="outline"
            size="sm"
            className="border-slate-800 bg-slate-900/80 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-mono"
          >
            {downloaded ? (
              <>
                <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                Summary Downloaded
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5 mr-1.5 text-blue-400" />
                Download Summary
              </>
            )}
          </Button>

          {/* Primary Action: Analyze Another Job */}
          <Button
            onClick={handleAnalyzeClick}
            size="sm"
            className="bg-[#00ff88] hover:bg-[#00cc6a] text-black font-semibold text-xs font-mono px-4 shadow-[0_0_15px_rgba(0,255,136,0.25)] hover:shadow-[0_0_20px_rgba(0,255,136,0.4)] transition-all cursor-pointer"
          >
            Analyze Another Job
            <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
          </Button>
        </div>
      </div>
    </div>
  );
}
